// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useEffect: typeof import('react')['useEffect']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
export {}
